export type Book = {
  title: string;
  author: string;
};

export type YearOfReading = {
  year: number;
  books: Book[];
};

export const READING: YearOfReading[] = [
  {
    year: 2026,
    books: [
      { title: "The Terraformers", author: "Annalee Newitz" },
      { title: "Seven Empty Houses", author: "Samanta Schweblin" },
      { title: "Big Hair and Plastic Grass", author: "Dan Epstein" },
      { title: "The Wayfinder", author: "Adam Johnson" },
      { title: "Exit Zero", author: "Marie-Helene Bertino" },
      { title: "The Decagon House Murders", author: "Yukito Ayatsuji" },
      { title: "The Employees", author: "Olga Ravn" },
      { title: "Vigil", author: "George Saunders" },
      { title: "Hip-Hop is History", author: "Questlove" },
      { title: "Seasons of Glass and Iron", author: "Amal El-Mohtar" },
      { title: "Small Things Like These", author: "Claire Keegan" },
      { title: "The Staircase in the Woods", author: "Chuck Wendig" },
      { title: "The Infinite Sadness of Small Appliances", author: "Glenn Dixon" },
      { title: "Concerning the Spiritual in Art", author: "Wassily Kandinsky" },
      { title: "When Trees Testify", author: "Beronda Montgomery" },
      { title: "The Left Hand of Darkness", author: "Ursula K. Le Guin" },
      { title: "With the Heart of a Ghost", author: "Lim Sunwoo" },
      { title: "Hum", author: "Helen Phillips" },
      { title: "Shroud", author: "Adrian Tchaikovsky" },
      { title: "Revenge", author: "Yoko Ogawa" },
      { title: "The Beauty of Everyday Things", author: "Soetsu Yanagi" },
      { title: "At the Edge of the Woods", author: "Kathryn Bromwich" },
      { title: "Between Two Fires", author: "Christopher Buehlman" },
      { title: "William Blake and The Sea Monsters of Love", author: "Philip Hoare" },
    ],
  },
  {
    year: 2025,
    books: [
      { title: "I Heard There Was a Secret Chord", author: "Daniel Levitin" },
      { title: "The Empusium", author: "Olga Tokarczuk" },
      { title: "Lesser Known Monsters of the 21st Century", author: "Kim Fu" },
      { title: "The Information", author: "James Gleick" },
      { title: "The God of the Woods", author: "Liz Moore" },
      { title: "Model Home", author: "Rivers Solomon" },
      { title: "James", author: "Percival Everett" },
      { title: "The Heaven & Earth Grocery Store", author: "James McBride" },
      { title: "Children of Time", author: "Adrian Tchaikovsky" },
      { title: "Entangled Life", author: "Merlin Sheldrake" },
      { title: "The Doloriad", author: "Missouri Williams" },
      { title: "Children of Ruin", author: "Adrian Tchaikovsky" },
      { title: "Children of Memory", author: "Adrian Tchaikovsky" },
      { title: "Light Eaters", author: "Zöe Schlanger" },
      { title: "North Woods", author: "Daniel Mason" },
      { title: "Same Bed Different Dreams", author: "Ed Park" },
      { title: "The Genius of Birds", author: "Jennifer Ackerman" },
      { title: "Counternarratives", author: "John Keene" },
      { title: "The Rise and Fall of the Dinosaurs", author: "Steve Brusatte" },
      { title: "The Neverending Story", author: "Michael Ende" },
      { title: "Orbital", author: "Samantha Harvey" },
      { title: "HHhH", author: "Laurent Binet" },
      { title: "Where the Axe is Buried", author: "Ray Nayler" },
      { title: "The Seventy Wonders of the Ancient World", author: "edited by Chris Sarre" },
      { title: "The Halloween Tree", author: "Ray Bradbury" },
      { title: "The Devourers", author: "Indra Das" },
      { title: "Murder on the Orient Express", author: "Agatha Christie" },
      { title: "Remarkably Bright Creatures", author: "Shelby Van Pelt" },
      { title: "Semiotics of Visual Language", author: "Fernande Saint-Martin" },
      { title: "Inventing the Renaissance", author: "Ada Palmer" },
      { title: "Mina’s Matchbox", author: "Yoko Ogawa" },
      { title: "Ingrained: The Making of a Craftsman", author: "Callum Robinson" },
    ],
  },
  {
    year: 2024,
    books: [
      { title: "Demon Copperhead", author: "Barbara Kingsolver" },
      { title: "Holes", author: "Louis Sachar" },
      { title: "Charlie and the Chocolate Factory", author: "Roald Dahl" },
      { title: "Major Labels: A History of Popular Music in Seven Genres", author: "Kelefa Sanneh" },
      { title: "The Memory Police", author: "Yoko Ogawa" },
      { title: "The MANIAC", author: "Benjamín Labatut" },
      { title: "Chain-Gang All-Stars", author: "Nana Kwame Adjei-Brenyah" },
      { title: "A Wrinkle in Time", author: "Madeleine L’Engle" },
      { title: "Itzá", author: "Rios de la Luz" },
      { title: "Brothas Be, Yo like George, Ain’t that Funkin’ Kinda Hard on You?", author: "George Clinton" },
      { title: "Darkly", author: "Leila Taylor" },
      { title: "Witches", author: "Brenda Lozano" },
      { title: "Harry Potter and the Sorcerer’s Stone", author: "J. K. Rowling" },
      { title: "On Michael Jackson", author: "Margo Jefferson" },
      { title: "Toad", author: "Kathleen Dunn" },
      { title: "The Seep", author: "Chana Porter" },
      { title: "Monstrilio", author: "Gerardo Sámano Córdova" },
      { title: "Divided Soul: The Life of Marvin Gaye", author: "David Ritz" },
      { title: "The Extinction of Irena Rey", author: "Jennifer Croft" },
      { title: "Trust", author: "Hernán Díaz" },
      { title: "The Tusks of Extinction", author: "Ray Nayler" },
      { title: "This Thing Between Us", author: "Gus Moreno" },
      { title: "Jonathan Strange & Mr Norrell", author: "Susanna Clarke" },
      { title: "They Flew", author: "Carlos Eire" },
      { title: "The Annual Banquet of Graverdiggers’ Guild", author: "Mathias Énard" },
      { title: "The System of Objects", author: "Jean Baudrillard" },
      { title: "Pest", author: "Michael Cisco" },
      { title: "Lapidarium", author: "Hettie Judah" },
      { title: "At the Mouth of the River of Bees", author: "Kij Johnson" },
      { title: "Absolution", author: "Jeff VanderMeer" },
      { title: "The Invention of Nature", author: "Andrea Wulf" },
      { title: "Harry Potter and the Chamber of Secrets", author: "J. K. Rowling" },
      { title: "Mercury Pictures Presents", author: "Anthony Marra" },
    ],
  },
  {
    year: 2023,
    books: [
      { title: "Fortune Smiles", author: "Adam Johnson" },
      { title: "The Lego Story", author: "Jens Andersen" },
      { title: "The Silver Chair", author: "C. S. Lewis" },
      { title: "The Abstainer", author: "Ian McGuire" },
      { title: "Cloud Cuckoo Land", author: "Anthony Doerr" },
      { title: "Metallica", author: "David Masciotra" },
      { title: "A Psalm for the Wild-Built", author: "Becky Chambers" },
      { title: "The Black Experience in Design", author: "Anne H. Berry, Kareem Collie, Penina Acayo Laker, Lesley-Ann Noel, Jennifer Rittner, Kelly Walters" },
      { title: "A Song for Everyone", author: "John Lingan" },
      { title: "Point B", author: "Drew Magary" },
      { title: "Walking Practice", author: "Dolki Min" },
      { title: "Popisho", author: "Leone Ross" },
      { title: "Shoe Dog", author: "Phil Knight" },
      { title: "Fat Time", author: "Jeffery Renard Allen" },
      { title: "Notes on the Synthesis of Form", author: "Christopher Alexander" },
      { title: "The Mountain in the Sea", author: "Ray Nayler" },
      { title: "Macunaíma", author: "Mário de Andrade" },
      { title: "The Unreality of Memory", author: "Elisa Gabbert" },
      { title: "Into the Void", author: "Geezer Butler" },
      { title: "Box Man", author: "Kōbō Abe" },
      { title: "Liberation Day", author: "George Saunders" },
      { title: "Otherlands", author: "Thomas Halliday" },
      { title: "Never Whistle at Night", author: "edited by Shane Hawk and Theodore C. Van Alst Jr." },
      { title: "Avoid the Day", author: "Jay Kirk" },
      { title: "Design: Purpose, Form, and Meaning", author: "John F. Pile" },
      { title: "One’s Company", author: "Ashley Hutson" },
      { title: "Lives of the Monster Dogs", author: "Kirsten Bakis" },
      { title: "A Prayer for the Crown-Shy", author: "Becky Chambers" },
    ],
  },
  {
    year: 2022,
    books: [
      { title: "The Communist Manifesto", author: "Karl Marx and Frederich Engels" },
      { title: "Piranesi", author: "Susanna Clarke" },
      { title: "Music is History", author: "Questlove" },
      { title: "Art + Faith", author: "Makoto Fujimura" },
      { title: "The Noblest Roman", author: "Jerry Kelly and Misha Beletsky" },
      { title: "No Gods, No Monsters", author: "Cadwell Turnbull" },
      { title: "Pizza Girl", author: "Jean Kyoung Frazier" },
      { title: "Meditations on First Philosophy", author: "René Descartes" },
      { title: "The Hobbit", author: "J.R.R. Tolkien" },
      { title: "On Heroes and Hero Worship and the Heroic in History", author: "Thomas Carlyle" },
      { title: "The Guide", author: "Peter Heller" },
      { title: "Writings on Media", author: "Stuart Hall" },
      { title: "The Hour of the Star", author: "Clarice Lispector" },
      { title: "The Dawn of Everything", author: "David Graeber and David Wengrow" },
      { title: "The Factory", author: "Hiroko Oyamada" },
      { title: "Devil House", author: "John Darnielle" },
      { title: "Flowers of Mold", author: "Ha Seong-nan" },
      { title: "Semiotics and the Philosophy of Language", author: "Umberto Eco" },
      { title: "Down Below", author: "Leonora Carrington" },
      { title: "Moon Witch Spider King", author: "Marlon James" },
      { title: "A Sign is Just a Sign", author: "Thomas Sebeok" },
      { title: "Player Piano", author: "Kurt Vonnegut" },
      { title: "Signs, Language, and Behavior", author: "Charles Morris" },
      { title: "The Kingdom of Speech", author: "Tom Wolfe" },
      { title: "Ethics", author: "Michael Cisco" },
      { title: "The Power of Babel: A Natural History of Language", author: "Jonny McWhorter" },
      { title: "Upgrade", author: "Blake Crouch" },
      { title: "Universe of the Mind", author: "Yuri Lotman" },
      { title: "The Day of the Triffids", author: "John Wyndham" },
      { title: "Sea of Tranquility", author: "Emily St. John Mandel" },
      { title: "Structuralism and Semiotics", author: "Terence Hawkes" },
      { title: "When We Cease to Understand the World", author: "Benjamín Labatut" },
      { title: "Ahab’s Return", author: "Jeffrey Ford" },
      { title: "The Greatest Invention", author: "Silvia Ferrera" },
      { title: "The Magician’s Nephew", author: "C. S. Lewis" },
      { title: "The Lion, the Witch, and the Wardrobe", author: "C. S. Lewis" },
      { title: "Prince Caspian", author: "C. S. Lewis" },
      { title: "Voyage of the* *Dawn Treader", author: "C. S. Lewis" },
      { title: "The 1619 Project", author: "Nikole Hannah-Jones" },
      { title: "Of Grammatology", author: "Jacques Derrida" },
    ],
  },
  {
    year: 2021,
    books: [
      { title: "The Arrest", author: "Jonathan Lethem" },
      { title: "A Place for Everything", author: "Judith Flanders" },
      { title: "Don’t Call it That", author: "Eli Altman" },
      { title: "The Hidden Girl and Other Stories", author: "Ken Liu" },
      { title: "Other Minds: The Octopus, The Sea, and The Deep Origins of Consciousness", author: "Peter Godfrey-Smith" },
      { title: "Enjoying the Bible", author: "Matthew Mullins" },
      { title: "The Shadow of the Torturer", author: "Gene Wolfe" },
      { title: "The Claw of the Conciliator", author: "Gene Wolfe" },
      { title: "A Swim in a Pond in the Rain", author: "George Saunders" },
      { title: "The Sword of the Lictor", author: "Gene Wolfe" },
      { title: "The Citadel of the Autarch", author: "Gene Wolfe" },
      { title: "Deacon King Kong", author: "James McBride" },
      { title: "Negative Space", author: "B. R. Yeager" },
      { title: "The Changeling", author: "Joy Williams" },
      { title: "The Red Pill", author: "Hari Kunzru" },
      { title: "The Traveler, The Tower, and The Worm", author: "Alberto Manguel" },
      { title: "Hummingbird Salamander", author: "Jeff VanderMeer" },
      { title: "Tokyo Ueno Station", author: "Yū Miri" },
      { title: "Morphology of the Folktale", author: "V. Propp" },
      { title: "Bug", author: "Giancomo Sartori" },
      { title: "Hollow", author: "B. Catling" },
      { title: "Swamplandia!", author: "Karen Russell" },
      { title: "Little Eyes", author: "Samanta Schweblin" },
      { title: "Beauty", author: "Roger Scruton" },
      { title: "The Intentional Father", author: "Jon Tyson" },
      { title: "Sorrowland", author: "Rivers Solomon" },
      { title: "The Hole", author: "Hiroko Oyamada" },
      { title: "Culture and Value", author: "Ludwig Wittgenstein" },
      { title: "Process and Reality", author: "Alfred North Whitehead" },
      { title: "All Fires the Fire", author: "Julio Cortázar" },
      { title: "33⅓: Led Zeppelin’s IV", author: "Erik Davis" },
      { title: "Levels of the Game", author: "John McPhee" },
      { title: "Night at the Fiestas", author: "Kirstin Valdez Quade" },
      { title: "Awakening Wonder: A Classical Guide to Truth, Goodness & Beauty", author: "Stephen R. Turley" },
      { title: "Metaphors We Live By", author: "George Lakoff and Mark Johnson" },
      { title: "The People in the Castle", author: "Joan Aiken" },
    ],
  },
  {
    year: 2020,
    books: [
      { title: "The Incompletes", author: "Sergio Chejfec" },
      { title: "Like a Thief in Broad Daylight: Power in the Era of Post-Human Capitalism", author: "Slavoj Žižek" },
      { title: "The Divinity Student", author: "Michael Cisco" },
      { title: "On Writing", author: "Jorge Luis Borges" },
      { title: "To Rouse Leviathan", author: "Matt Cardin and Mark McLaughlin" },
      { title: "Semiotic Animal: A postmodern definition of human being transcending Patriarchy and Feminism", author: "John Deely" },
      { title: "Myth and Meaning: Cracking the Code of Culture", author: "Claude Lévi-Strauss" },
      { title: "The Taiga Syndrome", author: "Christina Rivera Garza" },
      { title: "The Wounds of the Dead", author: "Vikram Paralkar" },
      { title: "Komodo", author: "Jeff VanderMeer" },
      { title: "A Natural History of Hell", author: "Jeffery Ford" },
      { title: "The Pocket Rumi", author: "edited by Kabir Helminski" },
      { title: "The Framework of Language", author: "Roman Jakobson" },
      { title: "The Glass Hotel", author: "Emily St John Mandel" },
      { title: "Loving to Know: Covenant Epistemology", author: "Esther Lightcap Meek" },
      { title: "Utopia", author: "Thomas More" },
      { title: "To Know As We Are Known", author: "Parker Palmer" },
      { title: "In the Seat of a Stranger's Car", author: "Beau Flemister" },
      { title: "Theory of Type Design", author: "Gerard Unger" },
      { title: "What the Heck is EOS?", author: "Gino Wickman" },
      { title: "Be The Bridge: Pursuing God’s Heart for Racial Reconciliation", author: "Latasha Morrison" },
      { title: "The Sellout", author: "Paul Beatty" },
      { title: "Earwig", author: "Brian Catling" },
      { title: "A Peculiar Peril", author: "Jeff VanderMeer" },
      { title: "This World is Full of Monsters", author: "Jeff VanderMeer" },
      { title: "The People in the Castle", author: "Joan Aiken" },
      { title: "Symbol, Myth, and Culture", author: "Ernst Cassirer" },
      { title: "Out of Body", author: "Jeffrey Ford" },
      { title: "Utopia Avenue", author: "David Mitchell" },
      { title: "The Houseguest", author: "Amparo Dávila" },
      { title: "Underland", author: "Robert Macfarlane" },
      { title: "Speaker of Ma’ila", author: "Trenton Anthony" },
      { title: "Stoner", author: "John Williams" },
      { title: "Thus Were Their Faces", author: "Silvia Ocampo" },
      { title: "The Silence", author: "Don DeLillo" },
      { title: "Signs", author: "Thomas Sebeok" },
      { title: "Under the Sea", author: "Mark Leidner" },
      { title: "Songs of a Dead Dreamer and Grimscribe", author: "Thomas Ligotti" },
      { title: "The Paper Menagerie", author: "Ken Liu" },
      { title: "Magic: A History", author: "Chris Gosden" },
      { title: "The Water Dancer", author: "Ta-Nehisi Coates" },
    ],
  },
  {
    year: 2019,
    books: [
      { title: "Fox 8", author: "George Saunders" },
      { title: "Mere Christianity", author: "C. S. Lewis" },
      { title: "Moderan", author: "David R. Bunch" },
      { title: "Air Guitar: Essays on Art and Democracy", author: "Dave Hickey" },
      { title: "Let’s Go (So We Can Get Back)", author: "Jeff Tweedy [audiobook]" },
      { title: "Anthem", author: "Ayn Rand" },
      { title: "Phantastes By George MacDonald", author: "" },
      { title: "Florida", author: "Lauren Groff" },
      { title: "Laws of Media: The New Science", author: "Marshall McLuhan and Eric McLuhan" },
      { title: "Mr. Pye", author: "Mervyn Peake" },
      { title: "The Stranger from Paradise: A Biography of William Blake", author: "G.E. Bentley" },
      { title: "The Wanderer", author: "Timothy J. Jarvis" },
      { title: "The Hero and the Outlaw: Building Extraordinary Brands Through the Power of Archetypes", author: "Margaret Mark and Carol Pearson" },
      { title: "Between The World and Me", author: "Ta-Nehisi Coates" },
      { title: "The Door to Saturn", author: "Clark Ashton Smith" },
      { title: "A Man Called Ove", author: "Fredrik Backman" },
      { title: "Member", author: "Michael Cisco" },
      { title: "An Alien Heat, Volume One of “The Dancers at the End of Time” by Michael Moorcock", author: "" },
      { title: "The Hollow Lands, Volume Two of “The Dancers at the End of Time” by Michael Moorcock", author: "" },
      { title: "The End of All Song, Volume Three of “The Dancers at the End of Time” by Michael Moorcock", author: "" },
      { title: "The Hero with a Thousand Faces", author: "Joseph Campbell" },
      { title: "The Alchemist", author: "Paulo Coelho" },
      { title: "Black Leopard, Red Wolf", author: "Marlon James" },
      { title: "Tremendous Trifles", author: "G. K. Chesterton" },
      { title: "ABC of Relativity", author: "Bertrand Russell" },
      { title: "The Old Man and the Sea", author: "Ernest Hemingway" },
      { title: "The Wide, Carnivorous Sky and Other Monstrous Geographies", author: "John Langan" },
      { title: "Half Gods", author: "Akil Kumarasamy" },
      { title: "The Light is the Darkness", author: "Laird Barron" },
      { title: "Recursion", author: "Blake Crouch" },
      { title: "Dead Souls", author: "Nikolai Gogol" },
      { title: "The Drowned Life", author: "Jeffrey Ford" },
      { title: "Reincarnation Blues", author: "Michael Poore" },
      { title: "33⅓:* *Master of Reality", author: "John Darnielle" },
      { title: "33⅓:* *Reign in Blood", author: "D. X. Ferris" },
      { title: "Fever Dream", author: "Samanta Schweblin" },
      { title: "Crackpot Palace", author: "Jeffrey Ford" },
      { title: "The Attributes of God", author: "A. W. Tozer" },
      { title: "African Folk Tales", author: "edited by Charlotte & Wolf Leslau" },
      { title: "Hawaiian Mythologies", author: "Martha Beckwith" },
      { title: "Circe", author: "Madeline Miller" },
      { title: "Upstream", author: "Mary Oliver" },
      { title: "Tell Them of Battles, Kings, and Elephants", author: "Mathias Énard" },
      { title: "Warren", author: "Brian Evenson" },
      { title: "The Only Harmless Great Thing", author: "Brooke Bolander" },
      { title: "Wood Beyond the World", author: "William Morris" },
      { title: "Dead Astronauts", author: "Jeff VanderMeer" },
      { title: "A Collapse of Horses", author: "Brian Evenson" },
      { title: "The Intuitionist", author: "Colson Whitehead" },
    ],
  },
  {
    year: 2018,
    books: [
      { title: "The Rings of Saturn", author: "W. G. Sebald" },
      { title: "Postmodernism in Pieces", author: "Matthew Mullins" },
      { title: "Mythologies", author: "Roland Barthes" },
      { title: "In The Distance", author: "Hernan Diaz" },
      { title: "The Changeling", author: "Victor LaValle" },
      { title: "The Secret Lives of Color", author: "Kassia St Clair" },
      { title: "The Water Knife", author: "Paolo Bacigalupi" },
      { title: "The 100-Year-Old Man Who Climbed Out the Window and Disappeared", author: "Jonas Jonasson" },
      { title: "The Accusation", author: "Bandi" },
      { title: "Semiotics: The Basics", author: "Daniel Chandler" },
      { title: "In Praise of Shadows", author: "Jun'ichirō Tanizaki" },
      { title: "The History of Bees", author: "Maja Lunde" },
      { title: "The Moon is Down", author: "John Steinbeck" },
      { title: "Language, Truth and Logic", author: "Alfred Jules Ayer" },
      { title: "The Narrator", author: "Michael Cisco" },
      { title: "When You Are Engulfed in Flames", author: "David Sedaris" },
      { title: "Elements of Semiology", author: "Roland Barthes" },
      { title: "In the River", author: "Jeremy Robert Johnson" },
      { title: "The Weight of Glory", author: "C. S. Lewis" },
      { title: "Crystal Eaters", author: "Shane Jones" },
      { title: "Contradict", author: "Andy Wrasman" },
      { title: "The Afflictions", author: "Vikram Paralkar" },
      { title: "White Tears", author: "Hari Kunzru" },
      { title: "The Solid Form of Language", author: "Robert Bringhurst" },
      { title: "East of Eden", author: "John Steinbeck" },
      { title: "Aickman’s Heirs", author: "edited by Simon Strantzas" },
      { title: "Ficciones", author: "Jorge Luis Borges" },
      { title: "Unlanguage", author: "Michael Cisco" },
      { title: "Meditations", author: "Marcus Aurelius" },
      { title: "The Shape of Things: A Philosophy of Design", author: "Vilém Flusser" },
      { title: "Largesse of the Sea Maiden", author: "Denis Johnson" },
      { title: "Embassytown", author: "China Miéville" },
      { title: "When Breath Becomes Air", author: "Paul Kalanithi" },
      { title: "The Cloven", author: "Brian Catling" },
      { title: "Walden", author: "Henry David Thoreau" },
      { title: "The Sisters Brothers", author: "Patrick DeWitt" },
      { title: "Blow-up, and other stories", author: "Julio Cortázar" },
      { title: "In The Darkroom", author: "Susan Faludi" },
      { title: "CivilWarLand in Bad Decline", author: "George Saunders" },
      { title: "Love in the Time of Cholera", author: "Gabriel García Márquez" },
      { title: "Deeper Into Pictures", author: "Flint Schier" },
      { title: "Wave", author: "Sonali Deraniyagala" },
      { title: "Kafka on the Shore", author: "Haruki Murakami" },
      { title: "A Little Manual for Knowing", author: "Esther Lightcap Meek" },
      { title: "Boy in Darkness, and Other Stories", author: "Mervyn Peake" },
      { title: "Jim Henson: The Biography", author: "Brian Jay Jones" },
      { title: "Crandolin", author: "Anna Tambour" },
      { title: "Book of Mercy", author: "Leonard Cohen" },
      { title: "Compass", author: "Mathias Énard" },
      { title: "Friday Black", author: "Nana Kwame Adjei-Brenyah" },
    ],
  },
  {
    year: 2017,
    books: [
      { title: "Time Travel", author: "James Gleick" },
      { title: "Don’t Read This Book", author: "Donald Roos" },
      { title: "A Constellation of Vital Phenomena", author: "Anthony Marra" },
      { title: "Sprint", author: "Jake Knapp" },
      { title: "Universal Harvester", author: "John Darnielle" },
      { title: "Culture Making", author: "Andy Crouch" },
      { title: "Benjamin Franklin", author: "Carl van Doren" },
      { title: "The Man Who Mistook His Wife for a Hat", author: "Oliver Sacks" },
      { title: "Symbols: A Handbook for Seeing", author: "Mark Fox and Angie Wang" },
      { title: "Dark Matter", author: "Blake Crouch" },
      { title: "Intercom on Starting Up", author: "Intercom" },
      { title: "Discipline and Punish", author: "Michel Foucault" },
      { title: "Borne: A Novel", author: "Jeff Vandermeer" },
      { title: "The Boats of the Glen Carrig", author: "William Hope Hodgson" },
      { title: "The Worm Ouroboros", author: "E. R. Eddison" },
      { title: "The Stranger", author: "Albert Camus" },
      { title: "This is Not a Pipe", author: "Michel Foucault" },
      { title: "What’s Best Next", author: "Matt Perman" },
      { title: "The Strange Bird", author: "Jeff Vandermeer" },
      { title: "Lincoln in the Bardo", author: "George Saunders" },
      { title: "The Vorrh", author: "Brian Catling" },
      { title: "Asteroid Made of Dragons of G. Derek Adams", author: "" },
      { title: "The Brief Wondrous Life of Oscar Wao", author: "Junot Díaz" },
      { title: "Bernini in Rome: Gian Lorenzo Bernini and the Baroque in Rome", author: "Paul den Arend" },
      { title: "The Erstwhile", author: "Brian Catling" },
      { title: "Brand New: The Shape of Brands to Come", author: "Wally Olins" },
      { title: "The North Water", author: "Ian McGuire" },
      { title: "The Library at Mount Char", author: "Scott Hawkins" },
      { title: "The Fisherman", author: "John Langan" },
      { title: "The Sarah Book", author: "Scott McLanahan" },
      { title: "Stephen Florida", author: "Gabe Habash" },
      { title: "The Bone Clocks", author: "David Mitchell" },
    ],
  },
  {
    year: 2016,
    books: [
      { title: "Goya", author: "Robert Hughes" },
      { title: "Reading Like A Writer", author: "Francine Prose" },
      { title: "The Presidency of George Washington", author: "Forrest McDonald" },
      { title: "Essentialism", author: "Greg McKeown" },
      { title: "Dissident Gardens", author: "Jonathan Lethem" },
      { title: "Station Eleven", author: "Emily St. John Mandel" },
      { title: "Language and Myth", author: "Ernst Cassirer" },
      { title: "Wonder", author: "A. J. Palacio" },
      { title: "The Orphan Master’s Son", author: "Adam Johnson" },
      { title: "Dog Stars", author: "Peter Heller" },
      { title: "The Everlasting Man", author: "G. K. Chesterton" },
      { title: "Area X: The Southern Reach: Annihilation", author: "Jeff Vandermeer" },
      { title: "Area X: The Southern Reach: Authority", author: "Jeff Vandermeer" },
      { title: "Area X: The Southern Reach: Acceptance", author: "Jeff Vandermeer" },
      { title: "The Divine Conspiracy", author: "Dallas Willard" },
      { title: "The Princess and The Goblin", author: "George MacDonald" },
      { title: "The Tsar of Love and Techno", author: "Anthony Marra" },
      { title: "The Great Divorce", author: "C. S. Lewis" },
      { title: "Slade House", author: "David Mitchell" },
      { title: "The Hike", author: "Drew Magary" },
      { title: "Zero K", author: "Don DeLillo" },
    ],
  },
  {
    year: 2015,
    books: [
      { title: "Simulacra and Simulation", author: "Jean Baudrillard" },
      { title: "Caravaggio: Painter of Miracles", author: "Francine Prose" },
      { title: "You and Me Forever", author: "Francis and Lisa Chan" },
      { title: "The Imperfectionists", author: "Tom Rachman" },
      { title: "Tenth of December", author: "George Saunders" },
      { title: "The Medium is the Massage", author: "Marshall McLuhan" },
      { title: "The Interestings", author: "Meg Wolitzer" },
      { title: "Wabi-Sabi for Artists, Designers, Poets, and Philosphers", author: "Leonard Koren" },
      { title: "Basics of Semiotics", author: "John Deely" },
      { title: "Orthodoxy", author: "G. K. Chesterton" },
      { title: "The Little Prince", author: "Antoine de Saint-Expuréry" },
      { title: "Stranger in a Strange Land", author: "Robert A. Heinlein" },
      { title: "Proof", author: "Daniel Montgomery and Timothy Paul Jones" },
      { title: "Go Set A Watchman", author: "Harper Lee" },
      { title: "Seventy-nine Short Essays on Design", author: "Michael Bierut" },
    ],
  },
  {
    year: 2014,
    books: [
      { title: "Color Psychology and Color Therapy", author: "Faber Birren" },
      { title: "Slaughterhouse-Five", author: "Kurt Vonnegut" },
      { title: "A Confederacy of Dunces", author: "John Kennedy Toole" },
      { title: "Paul Rand: Conversations with Students", author: "Michael Kroeger" },
      { title: "Emotional Branding", author: "Marc Gobé" },
      { title: "Just My Type", author: "Simon Garfield" },
      { title: "Wild at Heart", author: "John Eldredge" },
      { title: "The Strategic Designer", author: "David Holston" },
      { title: "Common Sense", author: "Thomas Paine" },
      { title: "Confessions", author: "St Augustine" },
      { title: "Love Wins", author: "Rob Bell" },
      { title: "Erasing Hell", author: "Francis Chan and Preston Sprinkle" },
      { title: "Manufacturing Consent", author: "Noam Chomsky and Edward Herman" },
      { title: "EntreLeadership", author: "Dave Ramsey" },
      { title: "Wolf in White Van", author: "John Darnielle" },
    ],
  },
  {
    year: 2013,
    books: [
      { title: "How To Be A Graphic Designer Without Losing Your Soul", author: "Adrian Shaughnessy" },
      { title: "The Elements of Typographic Style", author: "Robert Bringhurst" },
      { title: "God in a Cup: The Obsessive Quest for the Perfect Coffee", author: "Michaele Weissman" },
      { title: "Designing Brand Identity", author: "Alina Wheeler" },
      { title: "Brand Identity Essentials", author: "" },
      { title: "The Shape of Design", author: "Frank Chimero" },
      { title: "Design is a Job", author: "Joe Montero" },
      { title: "The 17 Essential Qualities of a Team Player", author: "John C. Maxwell" },
      { title: "ideaSelling", author: "Sam Harrison" },
      { title: "Ways of Seeing", author: "John Berger" },
      { title: "A Hologram for the King", author: "Dave Eggers" },
      { title: "Let The Great World Spin", author: "Colum McCann" },
      { title: "Design As Art", author: "Bruno Munari" },
      { title: "On Writing", author: "Stephen King" },
      { title: "The Creative Gift", author: "H. R. Rookmaaker" },
      { title: "The Beginner’s Guide to Colour Psychology", author: "Angela Wright" },
      { title: "Purity of the Heart is to Will One Thing", author: "Søren Kierkegaard" },
    ],
  },
];